# Generated by Django 4.2.1 on 2023-06-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=50)),
                ('qarz', models.PositiveSmallIntegerField(default=0)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('brend', models.CharField(max_length=100)),
                ('narx', models.IntegerField()),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('olchov', models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('qop', 'qop'), ('blok', 'blok')], max_length=30)),
                ('sana', models.CharField(max_length=100)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.ombor')),
            ],
        ),
    ]
