# Generated by Django 4.2.1 on 2023-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='sana',
            field=models.DateField(),
        ),
    ]
