# Generated by Django 4.2.1 on 2023-06-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0002_alter_mahsulot_sana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahsulot',
            old_name='ombor',
            new_name='ombor1',
        ),
        migrations.RenameField(
            model_name='mijoz',
            old_name='ombor',
            new_name='ombor1',
        ),
    ]
